name: GitHub Actions Doc Issue
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label Urgent
        uses: andymckay/labeler@5c59dabdfd4dd5bd9c6e6d255b01b9d764af4414
        with:
            bodyContains: 'documentation'
            add-labels: "documentation"

            repo-token: ${{ secrets.GITHUB_TOKEN }}
